name: Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate snake svg
        uses: Platane/snk@v1
        with:
          # repository: Platane/snk
          # file: README.md
          # action: update
          # add 2 arguments for the name of the repository
          repository: doyeldas

